# -*- coding: utf-8 -*-
"""LLM_RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d4NMf0GAF_Gdrdlcn7GbVZAEGz6LDYQ_
"""

import os

if 'COLAB_GPU' in os.environ:
 print("[INFO] running in Google Colab installing requirements.")
 !pip install PyMuPDF
 !pip install tqdm
 !pip install accelerate
 !pip install bitsandbytes
 !pip install flash-attn --no-build-isolation

#  !pip install -U torch
#  !pip install sentence-tranformers

!pip uninstall -y torch torchvision torchaudio transformers sentence-transformers
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
!pip install -U transformers sentence-transformers

import os
import requests

pdf_path = "human-nutrition-text.pdf"

if not os.path.exists(pdf_path):
  print("File doesn't exist, downloading...")

  url = "https://pressbooks.oer.hawaii.edu/humannutrition2/open/download?type=pdf"

  filename = pdf_path

  # Sending GET request
  response = requests.get(url)

  if response.status_code == 200:
    with open(filename, "wb") as file:
      file.write(response.content)
    print(f"The file has been downloaded and saved as {filename}")
  else:
    print(f"Failed to download the file. Status code: {response.status_code}")
else:
  print(f"File {pdf_path} exists.")

!pip uninstall fitz -y
!pip install -U pymupdf

import fitz

print(fitz.__file__)
print(hasattr(fitz, "open"))

"""### Reading the pdf"""

# Yimport fitz
# from tqdm.auto import tqdm

# def text_formatter(text: str) -> str:
#   """Minor formatting on text"""
#   cleaned_text = text.replace("\n", " ").strip()

#   return cleaned_text

# def open_and_Read_pdf(pdf_path: str) -> list[dict]:
#   doc = fitz.open(pdf_path)
#   pages_and_texts = []
#   for page_number, page in tqdm(enumerate(doc)):
#     text = page.get_text()
#     text = text_formatter(text)
#     pages_and_texts.append({
#         "page_number": page_number - 41,
#         "page_char_count": len(text),
#         "page_word_count": len(text.split()),
#         "page_sentence_count_raw": len(text.split(". ")),
#         "page_token_count": len(text) / 4,
#         "text": text
#     })

#   return pages_and_texts

# pages_and_texts = open_and_Read_pdf(pdf_path)

# Install once in Colab (run only if needed)
# !pip install -U pymupdf

import pymupdf as fitz
from tqdm.auto import tqdm

def text_formatter(text: str) -> str:
    """Minor formatting on text"""
    return text.replace("\n", " ").strip()

def open_and_read_pdf(pdf_path: str) -> list[dict]:
    doc = fitz.open(pdf_path)

    pages_and_texts = []

    for page_number, page in tqdm(enumerate(doc), total=len(doc)):
        text = page.get_text()
        text = text_formatter(text)

        pages_and_texts.append({
            "page_number": page_number,
            "page_char_count": len(text),
            "page_word_count": len(text.split()),
            "page_sentence_count_raw": len(text.split(". ")),
            "page_token_count": len(text) / 4,  # rough estimate
            "text": text
        })

    doc.close()
    return pages_and_texts

# Usage
# pdf_path = "/content/your_pdf_file.pdf"

pages_and_texts = open_and_read_pdf(pdf_path)

print(f"Pages processed: {len(pages_and_texts)}")
print(pages_and_texts[0]["text"][:500])

import pandas as pd

df = pd.DataFrame(pages_and_texts)
df.describe().round(2)

df.head()

"""## PART 2"""

!pip install spacy

from spacy.lang.en import English

nlp = English()
nlp.add_pipe("sentencizer")

doc = nlp("This is a sentence. This is another sentence.")
assert len(list(doc.sents)) == 2
list(doc.sents)

for item in tqdm(pages_and_texts):
  item["sentences"] = list(nlp(item["text"]).sents)

  item["sentences"] = [str(sentence) for sentence in item["sentences"]]

  item["page_sentence_count_spacy"] = len(item["sentences"])

import random
random.sample(pages_and_texts, k=1)

num_sentence_chunk_size = 10

def split_list(input_list: list, slice_size: int) -> list[list[str]]:
  return [input_list[i:i + slice_size] for i in range(0, len(input_list), slice_size)]

for item in tqdm(pages_and_texts):
  item["sentence_chunks"] = split_list(input_list=item["sentences"], slice_size=num_sentence_chunk_size)
  item["num_chunks"] = len(item["sentence_chunks"])

random.sample(pages_and_texts, k=1)

import re
pages_and_chunks = []

for item in tqdm(pages_and_texts):
  for sentence_chunk in item["sentence_chunks"]:
    chunk_dict = {}
    chunk_dict["page_number"] = item["page_number"]

    joined_sentence_chunk = "".join(sentence_chunk).replace("  ", " ").strip()
    joined_sentence_chunk = re.sub(r'\.([A-Z])', r'. \1', joined_sentence_chunk)
    chunk_dict["sentence_chunk"] = joined_sentence_chunk

    # Get stats about the chunk
    chunk_dict["chunk_char_count"] = len(joined_sentence_chunk)
    chunk_dict["chunk_word_count"] = len([word for word in joined_sentence_chunk])
    chunk_dict["chunk_token_count"] = len(joined_sentence_chunk) / 4

    pages_and_chunks.append(chunk_dict)
len(pages_and_chunks)

min_token_length = 30
df = pd.DataFrame(pages_and_chunks)

pages_and_chunks_over_min_token_len = df[df["chunk_token_count"] > min_token_length].to_dict(orient="records")
pages_and_chunks_over_min_token_len[:2]

!pip uninstall -y torchcodec
!pip install -q sentence-transformers

from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer(
    "sentence-transformers/all-mpnet-base-v2"
)

print("Model loaded successfully!")

from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer(model_name_or_path="sentence-transformers/all-mpnet-base-v2")

sentences = ["The sentences transformers library provides an easy.",
             "Sentences can be embedded one by one"]

embeddings = embedding_model.encode(sentences)
embeddings_dict = dict(zip(sentences, embeddings))

for sentence, embedding in embeddings_dict.items():
  print("Sentence", sentence)
  print("Embedding", embedding)
  print("")

text_chunks = [item["sentence_chunk"] for item in pages_and_chunks_over_min_token_len]

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# text_chunk_embeddings = embedding_model.encode(text_chunks,
#                                                batch_size=32,
#                                                convert_to_tensor=True)
# text_chunk_embeddings

